version: '3'
services:
  server1:
    image: nginx:latest
    container_name: nginx_server1
    networks:
      - shared-nw
    ports:
      - "8088:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
      - ./src/server1:/usr/share/nginx/html
    environment:
      TZ: Asia/Tokyo

  server2:
    image: nginx:latest
    container_name: nginx_server2
    networks:
      - shared-nw
    ports:
      - "8089:80"
    volumes:
      - ./docker/nginx2/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx2/log:/var/log/nginx
      - ./src/server2:/usr/share/nginx/html
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - server1
networks:
  shared-nw:
    external: true
